name: Package

on: [push, pull_request]

jobs:
  cmake:
    name: CMake package (${{ matrix.build_type }}, ${{ matrix.library_type }})
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        build_type: ["Debug", "Release"]
        library_type: ["static", "shared"]
    env:
      CMAKE_GENERATOR: Ninja
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: aminya/setup-cpp@v1
        with:
          ninja: true
      - name: Build and install open62541 & open62541pp
        run: |
          mkdir build
          cd build
          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} \
            -DBUILD_SHARED_LIBS=${{ matrix.library_type == 'shared' }} \
            ..
          cmake --build .
          sudo cmake --install .
      - name: Build examples (stand-alone)
        run: |
          mkdir build_examples
          cd build_examples
          cmake -G Ninja --debug-find ../examples
          cmake --build .
